[program:tripgenius]


directory=/var/www/TripGenius_Django
command=/var/www/TripGenius_Django/venv/bin/gunicorn \
tripgenius.wsgi:application \
--bind 127.0.0.1:8000 \
--workers 4
autostart=true

autorestart=true

stopasgroup=true

killasgroup=true

environment=DJANGO_SETTINGS_MODULE="tripgenius.settings"

stdout_logfile=/var/log/tripgenius/access.log

stderr_logfile=/var/log/tripgenius/error.log

user=www-data