# Generated by Django 4.2.23 on 2026-08-20 05:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TestCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='用例标题')),
                ('description', models.TextField(blank=True, default='', verbose_name='用例描述/前置条件')),
                ('case_type', models.CharField(choices=[('manual', '手动用例'), ('api', '接口用例')], default='manual', max_length=10)),
                ('priority', models.CharField(choices=[('P0', 'P0-阻塞'), ('P1', 'P1-严重'), ('P2', 'P2-一般'), ('P3', 'P3-轻微')], default='P2', max_length=2)),
                ('status', models.CharField(choices=[('active', '启用'), ('disabled', '停用')], default='active', max_length=10)),
                ('source', models.CharField(choices=[('manual', '手工编写'), ('ai', 'AI 生成'), ('scan', '接口扫描生成')], default='manual', max_length=10)),
                ('tags', models.JSONField(blank=True, default=list, verbose_name='标签')),
                ('method', models.CharField(blank=True, default='GET', max_length=10, verbose_name='请求方法')),
                ('endpoint', models.CharField(blank=True, default='', max_length=500, verbose_name='接口路径')),
                ('params', models.JSONField(blank=True, default=dict, verbose_name='请求参数')),
                ('expected_status', models.PositiveIntegerField(blank=True, null=True, verbose_name='预期状态码')),
                ('expected_keywords', models.JSONField(blank=True, default=list, verbose_name='预期响应关键字')),
                ('need_auth', models.BooleanField(default=True, verbose_name='执行前需登录')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
            ],
            options={
                'verbose_name': '测试用例',
                'verbose_name_plural': '测试用例',
                'ordering': ['-priority', '-created_time'],
            },
        ),
        migrations.CreateModel(
            name='TestSuite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='套件名称')),
                ('description', models.TextField(blank=True, default='', verbose_name='套件描述')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
            ],
            options={
                'verbose_name': '测试套件',
                'verbose_name_plural': '测试套件',
                'ordering': ['-created_time'],
            },
        ),
        migrations.CreateModel(
            name='TestExecution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='执行名称')),
                ('status', models.CharField(choices=[('pending', '待执行'), ('running', '执行中'), ('passed', '全部通过'), ('failed', '存在失败'), ('error', '执行异常')], default='pending', max_length=10)),
                ('total', models.IntegerField(default=0, verbose_name='用例总数')),
                ('passed', models.IntegerField(default=0, verbose_name='通过数')),
                ('failed', models.IntegerField(default=0, verbose_name='失败数')),
                ('skipped', models.IntegerField(default=0, verbose_name='跳过数')),
                ('duration', models.FloatField(default=0, verbose_name='耗时(秒)')),
                ('summary', models.TextField(blank=True, default='', verbose_name='执行摘要')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='开始时间')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='结束时间')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='执行人')),
                ('suite', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='qa.testsuite', verbose_name='关联套件')),
            ],
            options={
                'verbose_name': '测试执行',
                'verbose_name_plural': '测试执行',
                'ordering': ['-created_time'],
            },
        ),
        migrations.CreateModel(
            name='TestCaseResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_title', models.CharField(max_length=300, verbose_name='用例标题')),
                ('status', models.CharField(choices=[('passed', '通过'), ('failed', '失败'), ('skipped', '跳过'), ('error', '异常')], max_length=10)),
                ('duration', models.FloatField(default=0, verbose_name='耗时(秒)')),
                ('log', models.TextField(blank=True, default='', verbose_name='执行日志/失败信息')),
                ('analysis', models.TextField(blank=True, default='', verbose_name='AI 失败分析')),
                ('case', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='qa.testcase', verbose_name='用例')),
                ('execution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='qa.testexecution', verbose_name='所属执行')),
            ],
            options={
                'verbose_name': '用例执行结果',
                'verbose_name_plural': '用例执行结果',
            },
        ),
        migrations.AddField(
            model_name='testcase',
            name='suite',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cases', to='qa.testsuite', verbose_name='所属套件'),
        ),
    ]
